name: Terraform Apply

on:
  push:
    branches:
      - main # Adjust this to match the branch where you want to trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest # You can use other operating systems based on your requirements

    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Azure Login
        run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

      - name: Terraform init 
        run: terraform init -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -state="tfplan" -auto-approve
        env:
          ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
